# Generated by Django 4.1.3 on 2023-02-20 16:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_remove_customuser_votes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ping",
            name="date",
        ),
        migrations.AlterField(
            model_name="ping",
            name="voters",
            field=models.ManyToManyField(
                blank=True,
                default=None,
                null=True,
                related_name="related_voters",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
