# Generated by Django 4.1.3 on 2023-03-15 01:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_remove_ping_date_alter_ping_voters"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="alias",
            field=models.TextField(default="user", max_length=25),
        ),
        migrations.AlterField(
            model_name="ping",
            name="creator",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="related_creator",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="ping",
            name="voters",
            field=models.ManyToManyField(
                blank=True,
                default=None,
                related_name="related_voters",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
