# Generated by Django 4.1.3 on 2023-05-05 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_customuser_alias_alter_ping_creator_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ping",
            name="lat",
            field=models.DecimalField(decimal_places=20, max_digits=23),
        ),
        migrations.AlterField(
            model_name="ping",
            name="long",
            field=models.DecimalField(decimal_places=20, max_digits=23),
        ),
        migrations.AlterField(
            model_name="ping",
            name="ping_type",
            field=models.CharField(
                choices=[
                    ("pavement", "Pavement"),
                    ("road", "Road"),
                    ("scenary", "Scenary"),
                    ("busy", "Busy"),
                    ("litter", "Litter"),
                    ("wildlife", "Wildlife"),
                    ("shops", "Shops"),
                    ("other", "Other"),
                ],
                max_length=50,
            ),
        ),
    ]
