# Generated by Django 4.1.3 on 2023-05-05 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_alter_path_end_lat_alter_path_end_long_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="path",
            name="end_lat",
            field=models.DecimalField(decimal_places=6, max_digits=23),
        ),
        migrations.AlterField(
            model_name="path",
            name="end_long",
            field=models.DecimalField(decimal_places=6, max_digits=23),
        ),
        migrations.AlterField(
            model_name="path",
            name="start_lat",
            field=models.DecimalField(decimal_places=6, max_digits=23),
        ),
        migrations.AlterField(
            model_name="path",
            name="start_long",
            field=models.DecimalField(decimal_places=6, max_digits=23),
        ),
        migrations.AlterField(
            model_name="ping",
            name="lat",
            field=models.DecimalField(decimal_places=6, max_digits=23),
        ),
        migrations.AlterField(
            model_name="ping",
            name="long",
            field=models.DecimalField(decimal_places=6, max_digits=23),
        ),
    ]
