# Generated by Django 4.1.3 on 2023-05-06 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_alter_path_end_lat_alter_path_end_long_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ping",
            name="ping_type",
            field=models.CharField(
                choices=[
                    ("pavement", "Pavement"),
                    ("road", "Road"),
                    ("scenary", "Scenary"),
                    ("busy", "Busy"),
                    ("litter", "Litter"),
                    ("wildlife", "Wildlife"),
                    ("view", "View"),
                    ("other", "Other"),
                ],
                max_length=50,
            ),
        ),
    ]
