# Generated by Django 4.1.3 on 2023-05-07 07:46

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_alter_ping_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ping",
            name="rating",
            field=models.IntegerField(
                default=5,
                validators=[
                    django.core.validators.MaxValueValidator(10),
                    django.core.validators.MinValueValidator(0),
                ],
            ),
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=200)),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "ping",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.ping"
                    ),
                ),
            ],
        ),
    ]
